import { createPublicClient, decodeEventLog, encodeFunctionData, erc20Abi, getAddress, http, parseAbiItem, keccak256, type Address, type Hex } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import pool from "./db";
import { env } from "./env";

const NATIVE = "0x0000000000000000000000000000000000000000";
const client = createPublicClient({ transport: http(env.rhcRpcUrl, { timeout: 10_000, retryCount: 1 }) });
const transfer = parseAbiItem("event Transfer(address indexed from, address indexed to, uint256 value)");
type Job = { id:string; asset_address:string|null; asset_symbol:"ETH"|"TERA"; decimals:number; sender_address:string; recipient_address:string; amount:string; intake_address:string; payout_address:string; status:string; deposit_tx_hash:Hex|null; sweep_tx_hash:Hex|null; payout_tx_hash:Hex|null; sweep_serialized_tx:Hex|null; payout_serialized_tx:Hex|null; expires_at:string };
let running=false;
const validKey=(key:string)=>/^0x[\da-fA-F]{64}$/.test(key);
export const enabled=()=>Boolean(pool&&env.privateSendEnabled&&validKey(env.privateSendVaultPrivateKey)&&validKey(env.privateSendPayoutPrivateKey)&&/^0x[\da-fA-F]{40}$/.test(env.teraTokenAddress));
const intake=()=>privateKeyToAccount(env.privateSendVaultPrivateKey as Hex);
const payout=()=>privateKeyToAccount(env.privateSendPayoutPrivateKey as Hex);
const known=(e:unknown)=>/already known|known transaction|nonce too low/i.test(e instanceof Error?e.message:String(e));

async function receipt(hash:Hex){try{return await client.getTransactionReceipt({hash})}catch{return null}}
async function confirmed(hash:Hex){const r=await receipt(hash);if(!r)return null;if(r.status!=="success")throw Error("Routing transaction reverted on chain.");const head=await client.getBlockNumber();return head-r.blockNumber+1n>=BigInt(env.privateSendConfirmations)?r:null}
function token(job:Job){return job.asset_symbol==="TERA"?getAddress(env.teraTokenAddress):null}
function signedTx(job:Job, from:Address,to:Address){const amount=BigInt(job.amount);return job.asset_symbol==="ETH"?{to,value:amount,data:"0x" as Hex}:{to:getAddress(env.teraTokenAddress),value:0n,data:encodeFunctionData({abi:erc20Abi,functionName:"transfer",args:[to,amount]})}}
async function matches(job:Job, hash:Hex, from:Address, to:Address){const r=await confirmed(hash);if(!r)return false;const amount=BigInt(job.amount);if(job.asset_symbol==="ETH")throw Error("Native transfers must be verified separately.");
const t=token(job)!;return r.logs.some(log=>{if(getAddress(log.address)!==t)return false;try{const a=decodeEventLog({abi:[transfer],data:log.data,topics:log.topics}).args as {from:Address;to:Address;value:bigint};return getAddress(a.from)===from&&getAddress(a.to)===to&&a.value===amount}catch{return false}})}
async function nativeMatches(hash:Hex, from:Address,to:Address, amount:bigint){const r=await confirmed(hash);if(!r||getAddress(r.from)!==from||getAddress(r.to!)!==to)return false;const tx=await client.getTransaction({hash});return tx.value===amount}
async function depositReady(job:Job){const hash=job.deposit_tx_hash!;return job.asset_symbol==="ETH"?nativeMatches(hash,getAddress(job.sender_address),getAddress(job.intake_address),BigInt(job.amount)):matches(job,hash,getAddress(job.sender_address),getAddress(job.intake_address))}
async function sendStored(job:Job, phase:"sweep"|"payout"){if(!pool)throw Error("Private routing ledger unavailable.");const raw=phase==="sweep"?job.sweep_serialized_tx:job.payout_serialized_tx;if(!raw)throw Error("Missing persisted routing transaction.");let hash=keccak256(raw);try{hash=await client.sendRawTransaction({serializedTransaction:raw})}catch(e){if(!known(e)){if(/max fee per gas less than block base fee|fee too low|underpriced/i.test(e instanceof Error?e.message:String(e))){await pool.query(`UPDATE private_send_jobs SET status=$2,${phase}_serialized_tx=NULL,updated_at=NOW() WHERE id=$1`,[job.id,phase==="sweep"?"deposit_confirmed":"sweep_confirmed"]);}throw e;}}await pool.query(`UPDATE private_send_jobs SET status=$2,${phase}_tx_hash=$3,updated_at=NOW() WHERE id=$1`,[job.id,`${phase}_broadcast`,hash]);}
async function signPhase(job:Job, phase:"sweep"|"payout"){if(!pool)throw Error("Private routing ledger unavailable.");const signer=phase==="sweep"?intake():payout(), destination=getAddress(phase==="sweep"?job.payout_address:job.recipient_address), tx=signedTx(job,signer.address,destination);const [nonce,rawGasPrice]=await Promise.all([client.getTransactionCount({address:signer.address,blockTag:"pending"}),client.getGasPrice()]);const gasPrice=(rawGasPrice*130n)/100n+1000000n;const raw=await signer.signTransaction({...tx,nonce,gas:job.asset_symbol==="ETH"?21000n:100000n,gasPrice,chainId:env.rhcChainId});const hash=keccak256(raw);await pool.query(`UPDATE private_send_jobs SET status=$2,${phase}_serialized_tx=$3,${phase}_tx_hash=$4,updated_at=NOW() WHERE id=$1 AND status=$5`,[job.id,`${phase}_signed`,raw,hash,phase==="sweep"?"deposit_confirmed":"sweep_confirmed"]);return {...job,[`${phase}_serialized_tx`]:raw,[`${phase}_tx_hash`]:hash,status:`${phase}_signed`} as Job;}
export async function runPrivateSendExecutor(){if(running||!enabled()||!pool)return;running=true;const lock=await pool.connect();try{const got=await lock.query("SELECT pg_try_advisory_lock(hashtext('tera_private_send_executor')) AS locked");if(!got.rows[0]?.locked)return;try{await pool.query("UPDATE private_send_jobs SET status='expired',updated_at=NOW() WHERE status IN ('awaiting_deposit','deposit_pending') AND expires_at<=NOW()");const rows=await pool.query("SELECT * FROM private_send_jobs WHERE status IN ('deposit_pending','deposit_confirmed','sweep_signed','sweep_broadcast','sweep_confirmed','payout_signed','payout_broadcast') ORDER BY created_at LIMIT 10");for(const job of rows.rows as Job[]){try{if(job.status==='deposit_pending'){if(await depositReady(job))await pool.query("UPDATE private_send_jobs SET status='deposit_confirmed',updated_at=NOW() WHERE id=$1",[job.id])}else if(job.status==='deposit_confirmed')await sendStored(await signPhase(job,'sweep'),'sweep');else if(job.status==='sweep_signed')await sendStored(job,'sweep');else if(job.status==='sweep_broadcast'){const ok=job.asset_symbol==='ETH'?await nativeMatches(job.sweep_tx_hash!,getAddress(job.intake_address),getAddress(job.payout_address),BigInt(job.amount)):await matches(job,job.sweep_tx_hash!,getAddress(job.intake_address),getAddress(job.payout_address));if(ok)await pool.query("UPDATE private_send_jobs SET status='sweep_confirmed',updated_at=NOW() WHERE id=$1",[job.id])}else if(job.status==='sweep_confirmed')await sendStored(await signPhase(job,'payout'),'payout');else if(job.status==='payout_signed')await sendStored(job,'payout');else if(job.status==='payout_broadcast'){const ok=job.asset_symbol==='ETH'?await nativeMatches(job.payout_tx_hash!,getAddress(job.payout_address),getAddress(job.recipient_address),BigInt(job.amount)):await matches(job,job.payout_tx_hash!,getAddress(job.payout_address),getAddress(job.recipient_address));if(ok)await pool.query("UPDATE private_send_jobs SET status='confirmed',confirmed_at=NOW(),updated_at=NOW() WHERE id=$1",[job.id])}}catch(e){const reason=e instanceof Error?e.message:'Routing failed';if(/reverted/i.test(reason))await pool.query("UPDATE private_send_jobs SET status='failed',failure_reason=$2,updated_at=NOW() WHERE id=$1",[job.id,reason]);console.error('Private send job failed',job.id,e)}}}finally{await lock.query("SELECT pg_advisory_unlock(hashtext('tera_private_send_executor'))")}}finally{lock.release();running=false}}
export function startPrivateSendExecutor(){if(!enabled())return;void runPrivateSendExecutor();setInterval(()=>void runPrivateSendExecutor(),env.privateSendJobIntervalMs).unref()}
export async function creditPrivateDeposit(id:string,hash:Hex){if(!pool)throw Error("Private routing ledger unavailable.");const db=await pool.connect();try{await db.query('BEGIN');const found=await db.query("SELECT * FROM private_send_jobs WHERE id=$1 FOR UPDATE",[id]);const job=found.rows[0] as Job|undefined;if(!job)throw Error("Private send job not found.");if(!['awaiting_deposit','deposit_pending','deposit_confirmed'].includes(job.status))throw Error("Private send job cannot accept a deposit.");if(new Date(job.expires_at).getTime()<Date.now()&&job.status!=='deposit_confirmed')throw Error("Private send job expired.");if(job.deposit_tx_hash&&job.deposit_tx_hash.toLowerCase()!==hash.toLowerCase())throw Error("A different deposit hash is already attached to this job.");const next={...job,deposit_tx_hash:hash} as Job;await db.query("UPDATE private_send_jobs SET status=CASE WHEN status='deposit_confirmed' THEN status ELSE 'deposit_pending' END,deposit_tx_hash=$2,updated_at=NOW() WHERE id=$1",[id,hash]);if(!(await depositReady(next))){await db.query('COMMIT');return {status:'awaiting_confirmations'}}await db.query("UPDATE private_send_jobs SET status='deposit_confirmed',deposit_tx_hash=$2,updated_at=NOW() WHERE id=$1",[id,hash]);await db.query('COMMIT');return {status:'deposit_confirmed'}}catch(e){await db.query('ROLLBACK').catch(()=>{});throw e}finally{db.release()}}
export function addresses(){return {intakeAddress:intake().address,payoutAddress:payout().address}}
export { NATIVE };
